site_name: Health Monitoring API - Polyglot Reference Implementation
site_description:
site_author: Nitin Chaurasia
docs_dir: documentation/
repo_url: https://github.com/nitinkc/polyglot-health-monitor

theme:
  name: material
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    - scheme: default
      primary: brown
      accent: brown
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: brown
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - header.autohide
#    -  toc.integrate

plugins:
  - search
  - swagger-ui-tag
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      disable_indented_code_blocks: true
      custom_fences:
        - name: mermaid
          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_div_format # Does not work with mkdocs-material 9.0.0, so using the default format instead
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - abbr
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'div'

nav:
  - Home: index.md
  - Docs:
      - spec: spec.md
      - OpenAPI: API.md
  - Implementations:
      - Java: java-implementation.md
      - Go: go.md
      - Python: python.md
      - TypeScript: typescript.md